[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kaggle-mcp"
version = "0.0.1"
dependencies = [
    "pytest>=9.0.2",
]

[tool.setuptools]
packages = {find = {}}
